### ISSUE TITLE
cannot install in win10

### ISSUE THREAD

**Issue by xqyd** [YuliangXiu/neural_voxelization_layer#1]
Hi,
Thanks for sharing this!
I was trying to build it for icon project. But got errors when runing 'pip install git+https://github.com/YuliangXiu/neural_voxelization_layer.git' in my anaconda console.

Here's the output:

Collecting git+https://github.com/YuliangXiu/neural_voxelization_layer.git
  Cloning https://github.com/YuliangXiu/neural_voxelization_layer.git to c:\users\zyq\appdata\local\temp\pip-req-build-3331bc7q
  Running command git clone -q https://github.com/YuliangXiu/neural_voxelization_layer.git 'C:\Users\ZYQ\AppData\Local\Temp\pip-req-build-3331bc7q'
  Resolved https://github.com/YuliangXiu/neural_voxelization_layer.git to commit b3c054e378fcca4daf6a53aceeee7ef39e86318b
Building wheels for collected packages: voxelize-cuda
  Building wheel for voxelize-cuda (setup.py) ... error
ERROR: Command errored out with exit status 1:
   command: 'C:\Users\123\anaconda3\envs\icon2\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\123\\AppData\\Local\\Temp\\pip-req-build-3331bc7q\\setup.py'"'"'; __file__='"'"'C:\\Users\\123\\AppData\\Local\\Temp\\pip-req-build-3331bc7q\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\123\AppData\Local\Temp\pip-wheel-hs5ly5fz'
       cwd: C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\
  Complete output (23 lines):
  running bdist_wheel
  running build
  running build_ext
  C:\Users\123\anaconda3\envs\icon2\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
    warnings.warn(f'Error checking compiler version for {compiler}: {error}')
  building 'voxelize_cuda' extension
  creating C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build
  creating C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\temp.win-amd64-3.8
  creating C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\temp.win-amd64-3.8\Release
  creating C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\temp.win-amd64-3.8\Release\cuda
  Emitting ninja build file C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\temp.win-amd64-3.8\Release\build.ninja...
  Compiling objects...
  Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
  1.10.2
  creating C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\lib.win-amd64-3.8
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\123\anaconda3\envs\icon2\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\lib/x64" /LIBPATH:C:\Users\123\anaconda3\envs\icon2\libs /LIBPATH:C:\Users\123\anaconda3\envs\icon2 /LIBPATH:C:\Users\123\anaconda3\envs\icon2\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda_cu.lib torch_cuda_cpp.lib /EXPORT:PyInit_voxelize_cuda C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\temp.win-amd64-3.8\Release\cuda\voxelize_cuda.obj C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\temp.win-amd64-3.8\Release\cuda\voxelize_cuda_kernel.obj /OUT:build\lib.win-amd64-3.8\voxelize_cuda.cp38-win_amd64.pyd /IMPLIB:C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\temp.win-amd64-3.8\Release\cuda\voxelize_cuda.cp38-win_amd64.lib
  LINK : fatal error LNK1181: 无法打开输入文件“C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\temp.win-amd64-3.8\Release\cuda\voxelize_cuda.obj”
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181
  Error in atexit._run_exitfuncs:
  Traceback (most recent call last):
    File "C:\Users\123\anaconda3\envs\icon2\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
      return stream.closed
  ValueError: underlying buffer has been detached

  ----------------------------------------

  ERROR: Failed building wheel for voxelize-cuda
  Running setup.py clean for voxelize-cuda
Failed to build voxelize-cuda
Installing collected packages: voxelize-cuda
    Running setup.py install for voxelize-cuda ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\123\anaconda3\envs\icon2\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\123\\AppData\\Local\\Temp\\pip-req-build-3331bc7q\\setup.py'"'"'; __file__='"'"'C:\\Users\\123\\AppData\\Local\\Temp\\pip-req-build-3331bc7q\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\123\AppData\Local\Temp\pip-record-hauojk48\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\123\anaconda3\envs\icon2\Include\voxelize-cuda'
         cwd: C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\
    Complete output (25 lines):
    running install
    C:\Users\123\anaconda3\envs\icon2\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_ext
    C:\Users\123\anaconda3\envs\icon2\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
      warnings.warn(f'Error checking compiler version for {compiler}: {error}')
    building 'voxelize_cuda' extension
    creating C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build
    creating C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\temp.win-amd64-3.8
    creating C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\temp.win-amd64-3.8\Release
    creating C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\temp.win-amd64-3.8\Release\cuda
    Emitting ninja build file C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\temp.win-amd64-3.8\Release\build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    1.10.2
    creating C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\lib.win-amd64-3.8
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\123\anaconda3\envs\icon2\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\lib/x64" /LIBPATH:C:\Users\123\anaconda3\envs\icon2\libs /LIBPATH:C:\Users\123\anaconda3\envs\icon2 /LIBPATH:C:\Users\123\anaconda3\envs\icon2\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda_cu.lib torch_cuda_cpp.lib /EXPORT:PyInit_voxelize_cuda C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\temp.win-amd64-3.8\Release\cuda\voxelize_cuda.obj C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\temp.win-amd64-3.8\Release\cuda\voxelize_cuda_kernel.obj /OUT:build\lib.win-amd64-3.8\voxelize_cuda.cp38-win_amd64.pyd /IMPLIB:C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\temp.win-amd64-3.8\Release\cuda\voxelize_cuda.cp38-win_amd64.lib
    LINK : fatal error LNK1181: 无法打开输入文件“C:\Users\123\AppData\Local\Temp\pip-req-build-3331bc7q\build\temp.win-amd64-3.8\Release\cuda\voxelize_cuda.obj”
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "C:\Users\123\anaconda3\envs\icon2\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\123\anaconda3\envs\icon2\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\123\\AppData\\Local\\Temp\\pip-req-build-3331bc7q\\setup.py'"'"'; __file__='"'"'C:\\Users\\123\\AppData\\Local\\Temp\\pip-req-build-3331bc7q\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\123\AppData\Local\Temp\pip-record-hauojk48\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\123\anaconda3\envs\icon2\Include\voxelize-cuda' Check the logs for full command output.

Any idea what's caused this error?
Thanks and looking forward to hearing from you soon!

**Comment by Andyen512** [comment]
I met the same problem, do you know how to solve that?
